version: '3.8'
services:
  app:
    container_name: notes_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: notes_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: notes_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql  # Mounting your SQL script

volumes:
  postgres_data:
